workflows:
  ios-capacitor-workflow:
    name: iOS Build (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Code-magic # Confirme se o nome no painel tem o hífen
    environment:
      vars:
        BUNDLE_ID: "br.org.sestsenat.sisprec"
    scripts:
      - name: Install Dependencies
        script: npm install --legacy-peer-deps
      - name: Build Web App (Angular)
        script: npm run build:hom
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Set up Code Signing
        script: |
          keychain initialize
          # Removemos a flag problemática e adicionamos o comando para garantir 
          # que ele tente buscar o que for possível ou criar se permitido.
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create
          keychain add-certificates
      - name: Build iOS Native
        script: |
          # Adicionamos uma flag aqui para ignorar erros de assinatura automática 
          # caso o Xcode tente usar o certificado antigo do cache
          xcode-project build-ipa \
            --workspace ios/App/App.xcodeproj/project.xcworkspace \
            --scheme App \
            --allow-provisioning-updates
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - maxwellbezerra@sestsenat.org.br