workflows:
  ios-capacitor-workflow:
    name: iOS Build (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "br.org.sestsenat.sisprec"
        # Definimos o nome do certificado para que o Codemagic o identifique
        CERTIFICATE_NAME: "getec_sisprec"
    scripts:
      - name: Install Dependencies
        script: npm install --legacy-peer-deps
      - name: Build Web App (Angular)
        script: npm run build:hom
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Set up Code Signing
        script: |
          # Inicializa o keychain na máquina virtual
          keychain initialize
          # Busca e instala o certificado específico 'getec_sisprec' que você subiu
          keychain add-certificates
      - name: Build iOS Native
        script: |
          # O build-ipa agora usará o certificado getec_sisprec instalado acima
          xcode-project build-ipa \
            --workspace ios/App/App.xcodeproj/project.xcworkspace \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - maxwellbezerra@sestsenat.org.br